### ISSUE TITLE
Android APK Build Error

### ISSUE THREAD

**Issue by RejinR** [RobinCsl/build-standalone-expo-app#1]
Thanks for the great article. But I seem be having some problems in the final building process for an APK. I get an error stack like

> Jan 22 15:11:27 turtle[2546] ERROR: Error: write EPROTO 139864544790336:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
> 
> at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
> platform: "android"
> Jan 22 15:11:27 turtle[2546] ERROR: Failed to build standalone app
> err: Error: write EPROTO 139864544790336:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
>  at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)

How do I fix this?

**Comment by RejinR** [comment]
Nevermind. Fixed it..
I tried executing

> expo export --public-url http://127.0.0.1:8000

as given in the article. Since that gave an error, I used https which is why I got the error.

I then built it with --dev flag and it works fine.. :)

> expo export --dev --public-url http://127.0.0.1:8000 

is the right command
